//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameHandler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOMSEventFrameInterfaceEntities : DbContext
    {
        public MOMSEventFrameInterfaceEntities()
            : base("name=MOMSEventFrameInterfaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_factFailureDowntimeCMMS> tbl_factFailureDowntimeCMMS { get; set; }
        public virtual DbSet<tbl_DimNonWorkOrderDowntimeAnnnotations> tbl_DimNonWorkOrderDowntimeAnnnotations { get; set; }
        public virtual DbSet<tbl_DimSiteEquipment> tbl_DimSiteEquipment { get; set; }
    }
}
