//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameHandler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_factMaintenanceAnnotations
    {
        public int AID { get; set; }
        public string UniqueID { get; set; }
        public string WorkOrderID { get; set; }
        public string FailureTypeDescription { get; set; }
        public string FailureDescription { get; set; }
        public string RootCauseDescription { get; set; }
        public string RepairTypeDescription { get; set; }
        public string EquipmentType { get; set; }
        public string EquipmentNumber { get; set; }
        public string EquipmentName { get; set; }
        public System.DateTime ModifyStamp { get; set; }
        public string ModifyUser { get; set; }
    
        public virtual tbl_DimEquipmentType tbl_DimEquipmentType { get; set; }
    }
}
