//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameHandler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_factFailureDowntimeCMMS
    {
        public string UniqueID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Duration { get; set; }
        public string Equipment { get; set; }
        public string Equipment_Number { get; set; }
        public string Site { get; set; }
        public string Site_Area { get; set; }
        public string Site_Section { get; set; }
        public string Equipment_Type { get; set; }
        public string ElementID { get; set; }
        public Nullable<bool> IsEscalated { get; set; }
    }
}
