//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameHandler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DimSiteEquipment
    {
        public string ElementID { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentNumber { get; set; }
        public string EquipmentType { get; set; }
        public string Site { get; set; }
        public string SiteArea { get; set; }
        public string SiteSection { get; set; }
    }
}
