//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameHandler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DimNonWorkOrderDowntimeAnnnotations
    {
        public string Equipment { get; set; }
        public string Downtime_Type { get; set; }
        public string Root_Cause { get; set; }
        public string CKey { get; set; }
    }
}
