//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameHandler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DimNonWorkOrderDowntimeAnnnotations
    {
        public string Category { get; set; }
        public string DowntimeType { get; set; }
        public string RootCause { get; set; }
        public string Ckey { get; set; }
    }
}
